name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: stockify-android-webview

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Generate wrapper (if missing)
        run: |
          if [ ! -f gradlew ]; then
            gradle wrapper
          fi
        shell: bash

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug --no-daemon

      # Upload the produced APK as a build artifact
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: StockifySoufian-debug-apk
          path: stockify-android-webview/app/build/outputs/apk/debug/app-debug.apk
